name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit hooks (skip gitleaks)
        run: SKIP=gitleaks-staged pre-commit run --all-files

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1   # chỉ lấy commit mới nhất
      - name: Install gitleaks
        run: |
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
          | grep "browser_download_url.*linux-x64" \
          | cut -d '"' -f 4 \
          | wget -qi -
          tar -xvf gitleaks*linux-x64.tar.gz
          sudo mv gitleaks /usr/local/bin/
      - name: Run gitleaks scan (current files only)
        run: gitleaks detect --redact --no-git --source .




